apiVersion: v1
kind: ReplicationController
metadata:
  name: ltuengine76-rest
  labels:
    name: ltuengine76-rest
spec:
  replicas: 1
  selector:
    name: ltuengine76-rest
  template:
    metadata:
      labels:
        name: ltuengine76-rest
    spec:
      containers:
      - name: ltuengine76-rest
        # For custom build, change this value from a registry or local
        image: kubevision-ltu76-rest:batch-v1
        ports:
          - containerPort: 1979
            name: api
          - containerPort: 1980
            name: router
