apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-ui
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeUI"
  name: kube-ui
  namespace: default
spec:
  selector:
    k8s-app: kube-ui
  ports:
  - name: http
    nodePort: 30330
    port: 8003
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: NodePort
