# Kube Vision - Elasticsearch v1.7.2
svc_kube_elastic:
  build: svc_kube_elastic
  volumes:
    - /opt/kubeVision/data/:/var/lib/elasticsearch
  restart: always

# Kube Vision - Logstash 1.5.4
svc_kube_logstash:
  build: svc_kube_logstash
  volumes:
    - /opt/kubeVision/logs:/opt/logs
    - ./logstash/conf.d:/etc/logstash/conf.d
    - ./logstash/mappings:/etc/logstash/mappings
    - ./logstash/patterns:/opt/logstash/patterns_extra
  ports:
    - "5000:5000"
  links:
    - svc_kube_elastic
  restart: always

# Kube Vision - Kibana 4
svc_kube_kibana:
  build: svc_kube_kibana
  links:
    - svc_kube_elastic
  restart: always

# Kube Vision - Nginx Reverse Proxy for Kibana 4
svc_kube_proxy:
  build: svc_kube_proxy
  ports:
    - "1443:443"
  links:
    - svc_kube_kibana
  restart: always

# Kube Vision - Kube Forwarder
svc_kube_forwarder:
  build: svc_kube_forwarder
  links:
    - svc_kube_logstash
  volumes:
    - /opt/kubeVision/data/logs:/opt/logs
    - /usr/local/bin:/target

# Kube Vision - Haddop Partition
svc_kube_hdfs:
  build: svc_kube_hdfs
  command: /etc/bootstrap.sh -d -bash

# Kube Vision - Kube Graph / Mazrunner
svc_kube_mazerunner:
  build: svc_kube_mazerunner
  links:
   - svc_kube_hdfs

# Kube Vision - Kube Graph / Neo4j
svc_kube_graphdb:
  build: svc_kube_graphdb
  ports:
   - "7474:7474"
   - "1337:1337"
  volumes:
   - /opt/kubeVision/logs:/opt/logs
   - /opt/kubeVision/data:/opt/data
  links:
   - svc_kube_mazerunner
   - svc_kube_hdfs
