---
# Common tasks for every node
- include: common.yaml

- include: cadvisor.yaml
  when: "'master' in group_names or 'etcd' in group_names or 'apiserver' in group_names"

- include: kubectl.yaml
  when: "'master' in group_names or 'apiservers' in group_names or 'nodes' in group_names"

# Kubernetes apiserver specific tasks
- include: apiserver-binary.yaml
  when: "'apiservers' in group_names and hyperkube_deployment_mode == 'binary'"
- include: apiserver-docker.yaml
  when: "'apiservers' in group_names and hyperkube_deployment_mode == 'docker'"

# Kubernetes master specific tasks
- include: nginx-proxy.yaml
  when: "'master' in group_names"
- include: master-binary.yaml
  when: "'master' in group_names and hyperkube_deployment_mode == 'binary'"
- include: master-docker.yaml
  when: "'master' in group_names and hyperkube_deployment_mode == 'docker'"
- include: kraken-services.yaml
  when: "'master' in group_names"

# Kubernetes node and special node specific tasks
- include: node-pre.yaml
  when: "'nodes' in group_names"
- include: node-pre.yaml
  when: "'specialnodes' in group_names"
- include: node-binary.yaml
  when: "'nodes' in group_names and hyperkube_deployment_mode == 'binary'"
- include: node-binary.yaml
  when: "'specialnodes' in group_names and hyperkube_deployment_mode == 'binary'"
- include: node-docker.yaml
  when: "'nodes' in group_names and hyperkube_deployment_mode == 'docker'"
- include: node-docker.yaml
  when: "'specialnodes' in group_names and hyperkube_deployment_mode == 'docker'"
- include: node-post.yaml
  when: "'nodes' in group_names"
- include: node-post.yaml
  when: "'specialnodes' in group_names"
