apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: tectonic-ui
  name: tectonic-ui
  namespace: default
spec:
  replicas: 1
  selector:
    name: tectonic-ui
  template:
    metadata:
      labels:
        name: tectonic-ui
    spec:
      containers:
        - name: tectonic-ui
          image: 172.16.16.15:5000/tectonic-ui:latest
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
          command:
            - /opt/bridge/bin/bridge 
            - --k8s-endpoint=https://kubernetes
            - --public-dir=/opt/bridge/static
      nodeSelector:
        region: zone2
