apiVersion: v1
kind: Service
metadata:
  labels:
    name: tectonic-ui
  name: tectonic-ui
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 30380
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    name: tectonic-ui
  sessionAffinity: None
  type: NodePort

