---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: prometheus
  name: prometheus
  namespace: default
spec:
  ports:
  - name: prometheus
    nodePort: 30360
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: promdash
    nodePort: 30361
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: pushgateway
    port: 9091
    protocol: TCP
    targetPort: 9091
    nodePort: 30362
  selector:
    name: prometheus
  sessionAffinity: None
  type: NodePort
