FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install -y build-essential mercurial git subversion wget curl

# env vars

ENV GOPATH /goprojects
ENV PATH /goprojects/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

# go 1.5 tarball
RUN wget -qO- http://golang.org/dl/go1.5.1.linux-amd64.tar.gz | tar -C /usr/local -xzf -

# GOPATH
RUN mkdir -p /goprojects
RUN mkdir -p /goprojects/bin
RUN mkdir -p /goprojects/pkg
RUN mkdir -p /goprojects/src
RUN mkdir -p /goprojects/src/github.com

WORKDIR /goprojects/src/github.com/
