apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Locust
    name: load-generator-master
  name: load-generator-master
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 30341
    port: 8089
    protocol: TCP
    targetPort: 8089
  - name: slavecomm
    nodePort: 30342
    port: 5557
    protocol: TCP
    targetPort: 5557
  - name: slavecomm2
    nodePort: 30343
    port: 5558
    protocol: TCP
    targetPort: 5558
  selector:
    name: load-generator-master
  sessionAffinity: None
  type: NodePort
