apiVersion: v1
kind: Pod
metadata:
  labels:
    app: romulusd
  name: romulusd
spec:
  containers:
  - command:
    - /romulusd
    - --etcd=http://etcd-client:2379
    - --etcd-timeout=5s
    - --kube=http://127.0.0.1:8080
    - --svc-selector=romulus/type=external
    - --debug
    - --debug-etcd
    image: lucmichalski/kube-romulus:feature_middleware
    name: romulusd
  restartPolicy: Always
