apiVersion: v1
kind: Service
metadata:
  name: kube-vproxy
  annotations:
    romulus/pathRegexp: '/vproxy/maxfactor/.*'
    romulus/frontendSettings: '{"FailoverPredicate":"(IsNetworkError() || ResponseCode() == 503) && Attempts() <= 2"}}'
    romulus/backendSettings: '{"KeepAlive": {"MaxIdleConnsPerHost": 128, "Period": "4s"}}'
  labels:
    name: kube-vproxy
    romulus/vulcanKey: 'vulcand'
    romulus/type: external # <-- Will ensure SVC-SELECTORs specified (e.g. 'type=external') are present in Labels.
spec:
  ports:
  - name: middleware
    port: 8089
    protocol: TCP
    targetPort: 81
  - name: api
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: server
    port: 8082
    protocol: TCP
    targetPort: 802
  selector:
    app: kube-vproxy
