apiVersion: v1
kind: Service
metadata:
  labels:
    app: mungegithub
  name: submit-queue-status
  namespace: default
spec:
  clusterIP: 10.147.242.20
  ports:
  - name: status
    nodePort: 31624
    port: 80
    protocol: TCP
    targetPort: status
  selector:
    app: mungegithub
  sessionAffinity: None
  type: LoadBalancer
