apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: load-generator-slave
  name: load-generator-slave
  namespace: default
spec:
  replicas: 5
  selector:
    name: load-generator-slave
  template:
    metadata:
      labels:
        kubernetes.io/color: 0080FF
        name: load-generator-slave
    spec:
      containers:
      - command:
        - locust
        - -f
        - /scripts/locustfile.py
        - --slave
        - --master-host=load-generator-master
        - --host=http://framework:9080
        env:
        - name: INFLUXDB_HOST
          value: influxdb
        - name: INFLUXDB_PORT
          value: "8086"
        - name: INFLUXDB_USER
          value: root
        - name: INFLUXDB_PASSWORD
          value: root
        - name: INFLUXDB_NAME
          value: k8s
        image: quay.io/samsung_ag/trogdor-load-generator:latest
        imagePullPolicy: Always
        name: load-generator-slave
      dnsPolicy: ClusterFirst
      restartPolicy: Always
