apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: podpincher
  name: podpincher
  namespace: default
spec:
  replicas: 1
  selector:
    name: podpincher
  template:
    metadata:
      labels:
        kubernetes.io/color: FF33FF
        name: podpincher
    spec:
      containers:
      - image: 172.16.16.15:5000/podpincher:latest
        imagePullPolicy: Always
        name: podpincher
        env:
        - name: KUBERNETES_API_VER
          value: v1
        - name: KUBERNETES_API_URL
          value: https://kubernetes:443/api/
        ports:
        - containerPort: 4567
          hostPort: 4567
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        region: zone2
