---
- hosts: cluster
  gather_facts: False
  roles:
    - { role: ansible-coreos-bootstrap, coreos_pypy_url: 'https://bitbucket.org/squeaky/portable-pypy/downloads' }

- hosts: cluster
  gather_facts: True
  roles:
    - kubernetes

- hosts: localhost
  sudo: false
  roles:
    - ssh-config
